services:
  - type: web
    name: dental-laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: dental_database
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
